INSERT OR IGNORE INTO games (
  id, owner_id, publisher_id, title, slug, source_url, canonical_url,
  source_platform, status, visibility, description_short, student_goal,
  how_to_play, teacher_notes, subject, grade_min, grade_max, categories,
  skills, tags, activity_types, play_mode, embed_allowed, moderation_state,
  play_count, save_count, published_at, last_scanned_at
) VALUES
(
  'hammer', 'teacher-joseph', 'publisher-wellesley',
  'Where Is the Hammer?', 'where-is-the-hammer',
  'https://wellesley-games.pages.dev/hammer',
  'https://wellesley-games.pages.dev/hammer',
  'cloudflare', 'published', 'public',
  'Listen to each clue, scan the room and find the hidden hammer before the clock runs out.',
  'Use prepositions of place accurately while listening for classroom-object clues.',
  '["Listen to the location clue.","Discuss the answer with your team.","Tap the hiding place before time runs out."]',
  '["Excellent on a projector with two or three teams.","Ask for a complete sentence before revealing the answer."]',
  'English', 1, 3,
  '["Vocabulary","Speaking & Listening"]',
  '["Prepositions","Listening","Team play"]',
  '["classroom objects","projector","ESL"]',
  '["Team Race","Listening Game"]',
  'new_tab', 0, 'approved', 412, 96, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
  'castle', 'teacher-joseph', 'publisher-wellesley',
  'Castle Builder Grammar Race', 'castle-builder-grammar-race',
  'https://wellesley-games.pages.dev/castle',
  'https://wellesley-games.pages.dev/castle',
  'cloudflare', 'published', 'public',
  'Identify the tense, win a brick and build the tallest castle before the dragon round.',
  'Recognise past, present and future tense in complete sentences.',
  '["Read the sentence on the board.","Choose its tense as a team.","Correct answers add a brick to your castle."]',
  '["Use the dragon bonus round as an end-of-class reward.","Pause after a wrong answer and ask students to explain the clue."]',
  'English', 3, 5,
  '["Grammar","Team Games"]',
  '["Past tense","Present tense","Future tense"]',
  '["sentence building","review","ESL"]',
  '["Team Race","Multiple Choice"]',
  'new_tab', 0, 'approved', 388, 83, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
  'shark', 'teacher-joseph', 'publisher-wellesley',
  'Shark Alarm: Freeze Dance', 'shark-alarm-freeze-dance',
  'https://wellesley-games.pages.dev/shark',
  'https://wellesley-games.pages.dev/shark',
  'cloudflare', 'published', 'public',
  'Move while the music plays; freeze on the shark alarm and call out the target word.',
  'Respond to audio cues while recalling vocabulary under playful pressure.',
  '["Dance while the music plays.","Freeze when the shark alarm sounds.","Say the word shown to stay in the game."]',
  '["A reliable two-minute brain break."]',
  'Classroom Routines', 0, 2,
  '["Classroom Routines","ESL Warm-ups"]',
  '["Listening","Following instructions","Recall"]',
  '["movement","brain break","audio"]',
  '["Listening Game","Timed Challenge"]',
  'new_tab', 0, 'approved', 512, 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
  'tug', 'teacher-joseph', 'publisher-wellesley',
  'Tug of War: Addition Showdown', 'tug-of-war-addition-showdown',
  'https://wellesley-games.pages.dev/tugofwar',
  'https://wellesley-games.pages.dev/tugofwar',
  'cloudflare', 'published', 'public',
  'Every correct addition answer pulls the rope. Drag the other team over the line.',
  'Build addition fluency to 20 through quick, collaborative decisions.',
  '["Read the addition question.","Tap the answer before the other team.","Pull the flag across your line to win."]',
  '["Rotate the team tapper after each question."]',
  'Maths', 1, 3,
  '["Maths","Team Games"]',
  '["Addition to 20","Mental maths","Speed recall"]',
  '["addition","teams","fluency"]',
  '["Team Race","Timed Challenge"]',
  'new_tab', 0, 'approved', 347, 69, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
  'warp', 'teacher-joseph', 'publisher-wellesley',
  'Warp Speed Word Typer', 'warp-speed-word-typer',
  'https://wellesley-games.pages.dev/warp',
  'https://wellesley-games.pages.dev/warp',
  'cloudflare', 'published', 'public',
  'Type the falling words before they reach your ship and survive each faster wave.',
  'Improve spelling accuracy and keyboard fluency using levelled word lists.',
  '["Watch words drift toward the ship.","Type each word and press Enter.","Clear the wave to reach the next level."]',
  '["Best played with one keyboard per pair."]',
  'English', 4, 7,
  '["Spelling","Review Games"]',
  '["Spelling","Typing","Sight words"]',
  '["space","keyboard","literacy"]',
  '["Timed Challenge","Spelling"]',
  'new_tab', 0, 'approved', 198, 44, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
  'chengyu', 'teacher-joseph', 'publisher-wellesley',
  'Chengyu Galaxy', 'chengyu-galaxy',
  'https://wellesley-games.pages.dev/chengyu',
  'https://wellesley-games.pages.dev/chengyu',
  'cloudflare', 'published', 'school',
  'Travel through a galaxy of Chinese idioms, matching each chengyu to its meaning.',
  'Match common Chinese idioms to meanings and example situations.',
  '["Read the chengyu on the planet.","Choose the matching meaning.","Clear the sector to unlock its boss round."]',
  '["Boss rounds work well as a whole-class vote."]',
  'Languages', 5, 7,
  '["Vocabulary","Story Games"]',
  '["Chinese idioms","Reading","Meaning matching"]',
  '["chengyu","Mandarin","space"]',
  '["Multiple Choice","Board Game"]',
  'new_tab', 0, 'approved', 57, 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
