import type { Collection, Game, Publisher } from "@/lib/types";

const now = "2026-07-05T08:00:00.000Z";
const ownerId = "teacher-joseph";

export const publishers: Publisher[] = [
  {
    id: "publisher-wellesley",
    name: "Wellesley Games",
    slug: "wellesley-games",
    description:
      "Original classroom games created for lively, screen-ready lessons.",
    verified: true,
  },
  {
    id: "publisher-community",
    name: "Teacher Community",
    slug: "teacher-community",
    description: "Games shared by teachers using ClassBoard Games.",
    verified: false,
  },
];

const defaults = {
  ownerId,
  publisherId: "publisher-wellesley",
  canonicalUrl: "",
  status: "published" as const,
  visibility: "public" as const,
  screenshots: [] as string[],
  playMode: "new_tab" as const,
  embedAllowed: false,
  createdAt: now,
  updatedAt: now,
  publishedAt: now,
  lastScannedAt: now,
};

export const seedGames: Game[] = [
  {
    ...defaults,
    id: "hammer",
    title: "Where Is the Hammer?",
    slug: "where-is-the-hammer",
    sourceUrl: "https://wellesley-games.pages.dev/hammer",
    sourcePlatform: "cloudflare",
    descriptionShort:
      "Listen to each clue, scan the room and find the hidden hammer before the clock runs out.",
    studentGoal:
      "Use prepositions of place accurately while listening for classroom-object clues.",
    howToPlay: [
      "Listen to the location clue.",
      "Discuss the answer with your team.",
      "Tap the hiding place before time runs out.",
    ],
    teacherNotes: [
      "Excellent on a projector with two or three teams.",
      "Ask for a complete sentence before revealing the answer.",
    ],
    subject: "English",
    gradeMin: 1,
    gradeMax: 3,
    categories: ["Vocabulary", "Speaking & Listening"],
    skills: ["Prepositions", "Listening", "Team play"],
    tags: ["classroom objects", "projector", "ESL"],
    activityTypes: ["Team Race", "Listening Game"],
    accent: "blue",
    motif: "🔨",
    plays: 412,
    saves: 96,
  },
  {
    ...defaults,
    id: "castle",
    title: "Castle Builder Grammar Race",
    slug: "castle-builder-grammar-race",
    sourceUrl: "https://wellesley-games.pages.dev/castle",
    sourcePlatform: "cloudflare",
    descriptionShort:
      "Identify the tense, win a brick and build the tallest castle before the dragon round.",
    studentGoal:
      "Recognise past, present and future tense in complete sentences.",
    howToPlay: [
      "Read the sentence on the board.",
      "Choose its tense as a team.",
      "Correct answers add a brick to your castle.",
    ],
    teacherNotes: [
      "Use the dragon bonus round as an end-of-class reward.",
      "Pause after a wrong answer and ask students to explain the clue.",
    ],
    subject: "English",
    gradeMin: 3,
    gradeMax: 5,
    categories: ["Grammar", "Team Games"],
    skills: ["Past tense", "Present tense", "Future tense"],
    tags: ["sentence building", "review", "ESL"],
    activityTypes: ["Team Race", "Multiple Choice"],
    accent: "violet",
    motif: "🏰",
    plays: 388,
    saves: 83,
  },
  {
    ...defaults,
    id: "weather",
    title: "Weather Chart Quest",
    slug: "weather-chart-quest",
    sourceUrl: "https://chatgpt.com/share/weather-quest",
    sourcePlatform: "chatgpt",
    publisherId: "publisher-community",
    descriptionShort:
      "Read a weather chart, answer questions and unlock a new city with every accurate forecast.",
    studentGoal:
      "Read simple charts and use weather vocabulary in evidence-based answers.",
    howToPlay: [
      "Study the chart for ten seconds.",
      "Answer three questions about the data.",
      "Unlock the next city and a harder chart.",
    ],
    teacherNotes: ["Pair it with a real class weather diary."],
    subject: "Science",
    gradeMin: 2,
    gradeMax: 4,
    categories: ["Science", "Vocabulary"],
    skills: ["Weather vocabulary", "Reading charts", "Data talk"],
    tags: ["weather", "charts", "CLIL"],
    activityTypes: ["Multiple Choice", "Timed Challenge"],
    accent: "cyan",
    motif: "🌦️",
    plays: 265,
    saves: 61,
  },
  {
    ...defaults,
    id: "spinner",
    title: "Clothing Spin Game",
    slug: "clothing-spin-game",
    sourceUrl: "https://gemini.google.com/share/clothing-spin",
    sourcePlatform: "gemini",
    publisherId: "publisher-community",
    descriptionShort:
      "Spin the wheel, land on an outfit and build a vivid spoken description.",
    studentGoal:
      "Name and describe clothing using colour, size and complete sentences.",
    howToPlay: [
      "Spin the clothing wheel.",
      "Name and describe the item.",
      "Pass the next spin to another student.",
    ],
    teacherNotes: ["Model one rich description before beginning."],
    subject: "English",
    gradeMin: 0,
    gradeMax: 3,
    categories: ["Vocabulary", "Speaking & Listening"],
    skills: ["Clothing", "Descriptions", "Speaking"],
    tags: ["warm-up", "wheel", "young learners"],
    activityTypes: ["Roleplay", "Flashcard Game"],
    accent: "orange",
    motif: "👕",
    plays: 301,
    saves: 74,
  },
  {
    ...defaults,
    id: "shark",
    title: "Shark Alarm: Freeze Dance",
    slug: "shark-alarm-freeze-dance",
    sourceUrl: "https://wellesley-games.pages.dev/shark",
    sourcePlatform: "cloudflare",
    descriptionShort:
      "Move while the music plays; freeze on the shark alarm and call out the target word.",
    studentGoal:
      "Respond to audio cues while recalling vocabulary under playful pressure.",
    howToPlay: [
      "Dance while the music plays.",
      "Freeze when the shark alarm sounds.",
      "Say the word shown to stay in the game.",
    ],
    teacherNotes: ["A reliable two-minute brain break."],
    subject: "Classroom Routines",
    gradeMin: 0,
    gradeMax: 2,
    categories: ["Classroom Routines", "ESL Warm-ups"],
    skills: ["Listening", "Following instructions", "Recall"],
    tags: ["movement", "brain break", "audio"],
    activityTypes: ["Listening Game", "Timed Challenge"],
    accent: "navy",
    motif: "🦈",
    plays: 512,
    saves: 120,
  },
  {
    ...defaults,
    id: "tug",
    title: "Tug of War: Addition Showdown",
    slug: "tug-of-war-addition-showdown",
    sourceUrl: "https://wellesley-games.pages.dev/tugofwar",
    sourcePlatform: "cloudflare",
    descriptionShort:
      "Every correct addition answer pulls the rope. Drag the other team over the line.",
    studentGoal:
      "Build addition fluency to 20 through quick, collaborative decisions.",
    howToPlay: [
      "Read the addition question.",
      "Tap the answer before the other team.",
      "Pull the flag across your line to win.",
    ],
    teacherNotes: ["Rotate the team tapper after each question."],
    subject: "Maths",
    gradeMin: 1,
    gradeMax: 3,
    categories: ["Maths", "Team Games"],
    skills: ["Addition to 20", "Mental maths", "Speed recall"],
    tags: ["addition", "teams", "fluency"],
    activityTypes: ["Team Race", "Timed Challenge"],
    accent: "green",
    motif: "🪢",
    plays: 347,
    saves: 69,
  },
  {
    ...defaults,
    id: "warp",
    title: "Warp Speed Word Typer",
    slug: "warp-speed-word-typer",
    sourceUrl: "https://wellesley-games.pages.dev/warp",
    sourcePlatform: "cloudflare",
    descriptionShort:
      "Type the falling words before they reach your ship and survive each faster wave.",
    studentGoal:
      "Improve spelling accuracy and keyboard fluency using levelled word lists.",
    howToPlay: [
      "Watch words drift toward the ship.",
      "Type each word and press Enter.",
      "Clear the wave to reach the next level.",
    ],
    teacherNotes: ["Best played with one keyboard per pair."],
    subject: "English",
    gradeMin: 4,
    gradeMax: 7,
    categories: ["Spelling", "Review Games"],
    skills: ["Spelling", "Typing", "Sight words"],
    tags: ["space", "keyboard", "literacy"],
    activityTypes: ["Timed Challenge", "Spelling"],
    accent: "violet",
    motif: "🚀",
    plays: 198,
    saves: 44,
  },
  {
    ...defaults,
    id: "chengyu",
    title: "Chengyu Galaxy",
    slug: "chengyu-galaxy",
    sourceUrl: "https://wellesley-games.pages.dev/chengyu",
    sourcePlatform: "cloudflare",
    visibility: "school",
    descriptionShort:
      "Travel through a galaxy of Chinese idioms, matching each chengyu to its meaning.",
    studentGoal:
      "Match common Chinese idioms to meanings and example situations.",
    howToPlay: [
      "Read the chengyu on the planet.",
      "Choose the matching meaning.",
      "Clear the sector to unlock its boss round.",
    ],
    teacherNotes: ["Boss rounds work well as a whole-class vote."],
    subject: "Languages",
    gradeMin: 5,
    gradeMax: 7,
    categories: ["Vocabulary", "Story Games"],
    skills: ["Chinese idioms", "Reading", "Meaning matching"],
    tags: ["chengyu", "Mandarin", "space"],
    activityTypes: ["Multiple Choice", "Board Game"],
    accent: "navy",
    motif: "🪐",
    plays: 57,
    saves: 12,
  },
];

export const seedCollections: Collection[] = [
  {
    id: "wellesley",
    ownerId,
    title: "Wellesley Games",
    description: "The complete original Wellesley classroom collection.",
    gameIds: ["hammer", "castle", "shark", "tug", "warp", "chengyu"],
    visibility: "public",
  },
  {
    id: "friday",
    ownerId,
    title: "Friday Warm-ups",
    description: "Fast, upbeat openers requiring almost no preparation.",
    gameIds: ["spinner", "shark", "hammer"],
    visibility: "school",
  },
  {
    id: "grammar",
    ownerId,
    title: "Grammar on the Big Screen",
    description: "Whole-class language games for review lessons.",
    gameIds: ["castle", "hammer", "warp"],
    visibility: "private",
  },
];

export const subjects = [
  "English",
  "Maths",
  "Science",
  "Languages",
  "Classroom Routines",
];

export const categories = [
  "Vocabulary",
  "Grammar",
  "Speaking & Listening",
  "Phonics & Reading",
  "Maths",
  "Science",
  "Classroom Routines",
  "ESL Warm-ups",
  "Team Games",
  "Story Games",
  "Review Games",
];

export const activityTypes = [
  "Multiple Choice",
  "Team Race",
  "Timed Challenge",
  "Listening Game",
  "Roleplay",
  "Flashcard Game",
  "Board Game",
  "Spelling",
];
